package main

//go:generate swag init

import (
	"log"
	"net/http"

	"github.com/rs/cors"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	_ "api/docs"
	chi "github.com/go-chi/chi/v5"
	_ "github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/swaggo/http-swagger/v2"
)

// @title Shikimori Test API
// @version 1.0
// @description This is a Shikimori Test server.
// @termsOfService http://swagger.io/terms/

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /v1

func main() {

	r := chi.NewRouter()

	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"), //The url pointing to API definition
	))

	r.HandleFunc("/v1/test", sayhello)

	//mux := http.NewServeMux()
	r.HandleFunc("/hello", sayhello)
	//r.Handle("/", r)

	//h2cWrapper := &h2c.HandlerH2C{
	//	Handler:  cors.Default().Handler(mux),
	//	H2Server: &http2.Server{},
	//}

	http2Server := &http2.Server{}

	server := &http.Server{
		Addr:    ":8080",
		Handler: h2c.NewHandler(cors.Default().Handler(r), http2Server),
	}

	err := server.ListenAndServe()
	if err != nil {
		log.Fatal("ListenAndServe: ", err)
	}
}

func sayhello(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(200)
	w.Write([]byte("Hello World http2"))
}
