name: Terraform plan

on:
  workflow_dispatch:

jobs:
  terraform_plan:
    runs-on:
      - linux
      - X64
      - self-hosted

    container:
      image: hashicorp/terraform

    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      TF_VAR_access_key: ${{ secrets.SCW_ACCESS_KEY }}
      TF_VAR_secret_key: ${{ secrets.SCW_SECRET_KEY }}

    steps:
      - name: Check out git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Terraform plan
        run: | 
          cd terraform
          terraform init -backend-config="access_key=${{ secrets.SCW_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.SCW_SECRET_KEY }}"
          terraform plan

