name: Terraform apply

on:
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on:
      - linux
      - X64
      - self-hosted

    container:
      image: hashicorp/terraform

    env:
      TF_VAR_access_key: ${{ secrets.SCW_ACCESS_KEY }}
      TF_VAR_secret_key: ${{ secrets.SCW_SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY}}

    steps:
      - name: Check out git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Terraform apply
        run: |
          apk add make bash
          make terraform.plan
